service: python-crud
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:BatchWriteItem
      Resource: "*"
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
