service: python-crud
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:us-west-2:015111756483:table/users"
functions:
  find_all:
    handler: handler.find_all
    events:
      - httpApi:
          path: /all
          method: get
  insert:
    handler: handler.insert_users
    events:
      - httpApi:
          path: /users
          method: get
